const fs = require('fs')
const path = require('path')

const PROJECTS_DIR = path.join(
  __dirname,
  '..',
  '..',
  'ebook-generator',
  'projects'
)

function slugify(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function cleanBlurb(blurb) {
  if (!blurb) return ''
  return blurb
    .replace(/\n+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

const books = []

try {
  const projects = fs.readdirSync(PROJECTS_DIR)
  
  for (const projName of projects.sort()) {
    const projDir = path.join(PROJECTS_DIR, projName)
    const stat = fs.statSync(projDir)
    if (!stat.isDirectory()) continue
    
    const mjPath = path.join(projDir, 'manuscript.json')
    if (!fs.existsSync(mjPath)) continue
    
    const manuscript = JSON.parse(fs.readFileSync(mjPath, 'utf-8'))
    const meta = manuscript.meta || {}
    const hasPdf = fs.existsSync(path.join(projDir, 'book.pdf'))
    
    const slug = projName
    const title = meta.title || projName
    const subtitle = meta.subtitle || ''
    const author = meta.author || 'Manjunath Kalburgi'
    const blurb = cleanBlurb(meta.blurb)
    const chapters = meta.chapters ? meta.chapters.map(c => c.title) : []
    
    books.push({
      slug,
      title,
      subtitle,
      author,
      blurb,
      chapters,
      hasPdf,
      coverPng: `/covers/${slug}/cover.png`,
      // User must configure these:
      price: 9.99,
      currency: 'USD',
      stripeLink: '',
      driveLink: '',
    })
  }
  
  const outputPath = path.join(__dirname, '..', 'data', 'books.js')
  const content = `// Auto-generated by extract-books script\n// Edit price, stripeLink, and driveLink for each book\n\nmodule.exports = ${JSON.stringify(books, null, 2)}\n`
  
  fs.writeFileSync(outputPath, content)
  console.log(`Extracted ${books.length} books to ${outputPath}`)
} catch (err) {
  console.error('Error extracting books:', err.message)
  process.exit(1)
}
